### ISSUE TITLE
Consider using PHP's temp directory as default temp directory

### ISSUE THREAD

**Issue by joe-meyer** [monstahq/MONSTA-Box#14]
Instead of having a hard coded temp directory, I think you could make this work out of the box by leveraging the [sys_get_temp_dir()](http://php.net/manual/en/function.sys-get-temp-dir.php) function.

Something like this perhaps: `$serverTmp = sys_get_temp_dir();`

That or you should bundle a tmp directory with the application and instruct users to chmod it to be writable and default it to there. Making as much of the configuration as automatic as possible would be ideal.

**Comment by yiip87** [comment]
I've experimented with this setting and stumbled across an issue in which the `sys_get_temp_dir()` function may fail under certain circumstances. One example is a shared hosting environment with apache + mpm_prefork or mpm_itk + mod_php. To improve security on those systems, the systems /tmp directory is not writable for website users.  

Because of this every website user gets an own tmp directory (i.e. `/var/www/example.com/tmp`). However, `sys_get_tmp_dir()` does not recognise this 'user tmp' directory and continues to return the unwritable `/tmp` unless the evironment variable `TMPDIR` is set.  

This variable can be set in PHP before(!) `sys_get_tmp_dir()` or `tmpfile()` (which relies on the former) is first called:
```php
putenv("TMPDIR=/var/www/example.com/tmp");
```
Unfortunately, it is not possible to set this value via .htaccess or vhost configuration:
```sh
SetEnv TMPDIR "/var/www/example.com/tmp"
```
The funny thing is that when you use the above .htaccess snippet and put the following in the script, it will work without a problem:
```php
putenv('TMPDIR='.getenv('TMPDIR'));
```
I'm unable to reproduce this behaviour on systems where PHP is running with mod_fcgid or php-fpm.

> That or you should bundle a tmp directory with the application and instruct users to chmod it to be writable and default it to there.

I think this would be the best solution here. Most major CMS systems like Joomla, Typo3 or Wordpress are doing the same,

**Comment by EC-Joe** [comment]
Ya i'd agree that it's probably easiest and most reliable to simply bundle a tmp directory with the application for storage. Then if people wanted to change it to use /tmp/ there's no reason they couldn't but to ensure that things work sort of out of the box, it's best to have something already there I think. 

relying on .htaccess or vhost isn't always a good answer especially when you start running php on IIS or other web servers that don't utilize these.
